name: Daily Stock Pipeline

on:
  schedule:
    - cron: '0 2 * * *'  # runs at 2am UTC = 7:30am IST
  workflow_dispatch:       # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          POSTGRES_HOST: ${{ secrets.SUPABASE_HOST }}
          POSTGRES_PORT: ${{ secrets.SUPABASE_PORT }}
          POSTGRES_DB: ${{ secrets.SUPABASE_DB }}
          POSTGRES_USER: ${{ secrets.SUPABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: python main.py
